"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['lid_nid_mapper_app.py']
DATA_FILES = ['segment_names.csv']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'logoapp.icns',
    'packages': ['lid_nid_gui','lid_nid_helper_functions','snowflake_utility','lid_nid_config'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
